#!/usr/bin/env python3
"""
Build a TOML hierarchy mapping SOURCE domain names to WordNet synsets.

Structure (flat array-of-tables):

  [[domains]]
  name       = "BIRD"        # domain identifier (thesaurus name, or DOMAIN-N for splits)
  pos        = "n"
  synset_id  = "omw-en-..."  # empty for grouping nodes and POS roots
  hypernym   = "N_TOP"       # parent domain name ("" for roots)
  definition = "..."

Hierarchy rules
  - POS root nodes (N_TOP, V_TOP, A_TOP, R_TOP) have hypernym = "".
  - Single-synset domains start under their POS root; WordNet ancestry then
    promotes them under the most specific existing domain whose synset is a
    WN ancestor of theirs (e.g. WATERBIRD → BIRD).
  - Multi-synset domains produce a grouping node (synset_id = "") plus child
    leaves DOMAIN-1, DOMAIN-2, … that always point to the grouping node.

Usage:
  uv run scripts/build_domain_map.py
  uv run scripts/build_domain_map.py --min-count 2 --out build/source_domain_map.toml
"""

import argparse
import json
import sys
from collections import defaultdict
from functools import lru_cache
from pathlib import Path

import wn

sys.path.insert(0, str(Path(__file__).parent))
from wordnet_match import setup_wn


# ---------------------------------------------------------------------------
# POS root names
# ---------------------------------------------------------------------------

POS_TOPS: dict[str, str] = {
    "n": "N_TOP",
    "v": "V_TOP",
    "a": "A_TOP",
    "r": "R_TOP",
}


# ---------------------------------------------------------------------------
# Synset lookup
# ---------------------------------------------------------------------------

@lru_cache(maxsize=None)
def get_synset(sid: str) -> object | None:
    try:
        return wn.synset(sid)
    except wn.Error:
        return None


# ---------------------------------------------------------------------------
# TOML writer
# ---------------------------------------------------------------------------

def _toml_str(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def write_domain_map_toml(entries: list[dict], path: Path) -> None:
    """Write flat [[domains]] array-of-tables."""
    lines = [
        "# Source domain hierarchy → WordNet synsets",
        "# Generated by scripts/build_domain_map.py",
        "#",
        "# Each [[domains]] entry:",
        "#   name       — domain identifier (thesaurus name, or DOMAIN-N for splits)",
        "#   hypernym   — parent domain name (\"\" = root node)",
        "#   synset_id  — WordNet synset (empty for grouping nodes and roots)",
        "",
    ]
    for e in entries:
        lines.append("[[domains]]")
        lines.append(f'name       = "{_toml_str(e["name"])}"')
        lines.append(f'pos        = "{_toml_str(e["pos"])}"')
        lines.append(f'synset_id  = "{_toml_str(e["synset_id"])}"')
        lines.append(f'hypernym   = "{_toml_str(e["hypernym"])}"')
        lines.append(f'definition = "{_toml_str(e["definition"])}"')
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build SOURCE domain hierarchy → WordNet synset TOML map"
    )
    parser.add_argument("--input",     default="build/thesaurus_wn.json")
    parser.add_argument("--out",       default="build/source_domain_map.toml")
    parser.add_argument("--min-count", type=int, default=2,
                        help="Ignore synsets matched fewer than N times (default: 2)")
    args = parser.parse_args()

    setup_wn()
    data = json.loads(Path(args.input).read_text())

    # ── 1. Collect source_hits[DOMAIN][synset_id] = {count, definition} ──────
    source_hits: dict[str, dict] = defaultdict(
        lambda: defaultdict(lambda: {"count": 0, "definition": ""})
    )
    for part in data["parts"]:
        for theme in part["themes"]:
            for sub in theme["subsections"]:
                for entry in sub["entries"]:
                    lit = entry.get("wn_literal")
                    if not lit:
                        continue
                    for domain, hit in lit["scores"].get("hyper_matched", {}).items():
                        rec = source_hits[domain][hit["synset_id"]]
                        rec["count"] += 1
                        rec["definition"] = hit["definition"]

    print(f"Found {len(source_hits)} source domains with hypernym matches.")

    # ── 2. Group by POS, apply min_count ─────────────────────────────────────
    # domain_synsets[domain][pos] = [(ss, count, definition), ...]  desc by count
    domain_synsets: dict[str, dict[str, list]] = {}

    for domain, synset_counts in sorted(source_hits.items()):
        by_pos: dict[str, list] = defaultdict(list)
        for sid, rec in synset_counts.items():
            ss = get_synset(sid)
            if ss is not None:
                by_pos["a" if ss.pos == "s" else ss.pos].append((ss, rec["count"], rec["definition"]))

        if not by_pos:
            continue

        domain_synsets[domain] = {}
        for pos, entries in sorted(by_pos.items()):
            qualified = [(ss, cnt, defn) for ss, cnt, defn in entries
                         if cnt >= args.min_count]
            if not qualified:
                qualified = [max(entries, key=lambda x: x[1])]
            qualified.sort(key=lambda x: x[1], reverse=True)
            domain_synsets[domain][pos] = qualified

    # ── 3. Build flat entry list ──────────────────────────────────────────────
    all_pos = {pos for pm in domain_synsets.values() for pos in pm}
    used_tops = {POS_TOPS.get(pos, f"{pos.upper()}_TOP") for pos in all_pos}

    entries: list[dict] = []

    # POS root nodes first (in a stable order)
    for top in ["N_TOP", "V_TOP", "A_TOP", "R_TOP"]:
        if top in used_tops:
            pos_for_top = next(p for p, t in POS_TOPS.items() if t == top and p != "s")
            entries.append({
                "name": top, "pos": pos_for_top,
                "synset_id": "", "hypernym": "", "definition": "",
            })

    # Track indices of single-leaf entries for ancestry inference
    # key = (domain_name, pos) → index in `entries`
    single_leaf_indices: dict[tuple[str, str], int] = {}

    for domain, pos_map in sorted(domain_synsets.items()):
        for pos, synsets in sorted(pos_map.items()):
            top = POS_TOPS.get(pos, f"{pos.upper()}_TOP")

            if len(synsets) == 1:
                ss, cnt, defn = synsets[0]
                idx = len(entries)
                entries.append({
                    "name":       domain,
                    "pos":        pos,
                    "synset_id":  ss.id,
                    "hypernym":   top,       # may be refined in step 4
                    "definition": defn or ss.definition() or "",
                })
                single_leaf_indices[(domain, pos)] = idx

            else:
                # Grouping node (no synset_id); children carry the synsets
                entries.append({
                    "name":       domain,
                    "pos":        pos,
                    "synset_id":  "",
                    "hypernym":   top,
                    "definition": "",
                })
                for i, (ss, cnt, defn) in enumerate(synsets, 1):
                    child_name = f"{domain}-{i}"
                    entries.append({
                        "name":       child_name,
                        "pos":        pos,
                        "synset_id":  ss.id,
                        "hypernym":   domain,
                        "definition": defn or ss.definition() or "",
                    })

    # ── 4. Infer WordNet-based hypernyms for single-leaf entries ─────────────
    # Build synset_id → canonical domain name:
    #   single leaves  → their own domain name
    #   children of grouping nodes → their parent (grouping node) name
    # This allows e.g. WATERBIRD to find BIRD even when BIRD has no synset
    # directly (its children BIRD-1, BIRD-2 … cover the Aves synset).
    pos_top_names = set(POS_TOPS.values())

    synset_to_canonical: dict[str, str] = {}
    # Single leaves
    for (name, _pos), idx in single_leaf_indices.items():
        synset_to_canonical[entries[idx]["synset_id"]] = name
    # Children of grouping nodes (hypernym is a domain, not a POS root or "")
    for e in entries:
        if (e["synset_id"]
                and e["hypernym"]
                and e["hypernym"] not in pos_top_names
                and e["synset_id"] not in synset_to_canonical):
            synset_to_canonical[e["synset_id"]] = e["hypernym"]

    updated = 0
    for (name, pos), idx in single_leaf_indices.items():
        e = entries[idx]
        ss = get_synset(e["synset_id"])
        if ss is None:
            continue
        depth_map: dict[str, int] = {}
        for path in ss.hypernym_paths():
            for i, anc in enumerate(path):
                d = i + 1
                if anc.id not in depth_map or d < depth_map[anc.id]:
                    depth_map[anc.id] = d
        # Find domains (or grouping-node parents) whose synset is a strict ancestor
        candidates = [
            (synset_to_canonical[sid], depth)
            for sid, depth in depth_map.items()
            if sid in synset_to_canonical and synset_to_canonical[sid] != name
        ]
        if candidates:
            # Most specific = smallest depth (closest ancestor)
            best_domain = min(candidates, key=lambda x: x[1])[0]
            e["hypernym"] = best_domain
            updated += 1

    print(f"Updated {updated} domain hypernyms via WordNet ancestry.")

    # ── 5. Write TOML ─────────────────────────────────────────────────────────
    out_path = Path(args.out)
    write_domain_map_toml(entries, out_path)

    n_synset  = sum(1 for e in entries if e["synset_id"])
    n_group   = sum(1 for e in entries if not e["synset_id"]
                    and not e["name"].endswith("_TOP"))
    n_top     = sum(1 for e in entries if e["name"].endswith("_TOP"))
    print(f"Wrote {len(entries)} entries: "
          f"{n_top} POS roots, {n_synset} with synsets, "
          f"{n_group} grouping nodes → {out_path}")


if __name__ == "__main__":
    main()
